### ISSUE TITLE
Support newer FreeBSD and add support for Solaris (OpenIndiana) and DragonflyBSD

### ISSUE THREAD

**Issue by CretinHo** [freebasic/fbfrog#7]
Please consider update your FreeBSD defines. It's currently target FreeBSD 10. FreeBSD already has FreeBSD 13 released now. And please add support for Solaris (OpenIndiana) and DragonflyBSD, currently they are not on the list of available targets. Thanks.

**Comment by rversteegen** [comment]
Are you referring to the fact that fbfrog defines
```
	#define __FreeBSD__ 10
	#define __FreeBSD_cc_version 1000001
```
What's the effect of this? Do some system include files or library headers expose functionality based on these?
FreeBSD seems to be the only OS for which fbfrog sets a define to imitate a specific version of the OS.

**Comment by CretinHo** [comment]
> Are you referring to the fact that fbfrog defines
> 
> ```
> 	#define __FreeBSD__ 10
> 	#define __FreeBSD_cc_version 1000001
> ```
> 
> What's the effect of this? Do some system include files or library headers expose functionality based on these?
> FreeBSD seems to be the only OS for which fbfrog sets a define to imitate a specific version of the OS.

Yes, based on the version strings, system include files and library headers expose the appropriate functionality.
DragonflyBSD being a fork of FreeBSD, uses the same mechanic.
OpenIndiana being on the Solaris famility, also make use of even more defines to expose the appropriate functionality.

**Comment by rversteegen** [comment]
I don't see a reason to close this. fbfrog should support the same OSes that fbc does, and I assume it's safe to bump the FreeBSD version (though that's more relevant to fbbindings).
